name       : network-manager-applet
version    : 1.20.0
release    : 42
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.20/network-manager-applet-1.20.0.tar.xz : 8ab205385d8380e3b7e4994b46f6ff009c453e3430bd2b2853c74263f69a5253
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager Applet
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
setup      : |
    %patch -p1 < $pkgfiles/editor-fix-crash-when-evaluating-secondaries.patch
    %meson_configure --sysconfdir=/usr/share/ -Dappindicator=no -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
