name       : network-manager-applet
version    : 1.8.10
release    : 26
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.8/network-manager-applet-1.8.10.tar.xz : 0adc4bfae8b49f7a1d929c22ef20933bd41fb4a8b458280f44c65f9e45b4c9c3
license    : GPL-2.0
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager applet and GTK3 libraries
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
    - gtk-doc
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %apply_patches
    %meson_configure -Dlibnm-gtk=true -Dselinux=false
build      : |
    %meson_build
install    : |
    %meson_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
