name       : network-manager-applet
version    : 1.8.18
release    : 31
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.8/network-manager-applet-1.8.18.tar.xz : 23dc1404f1e0622b7c4718b6d978b101d5e4d9be0b92133b3863a4dc29786178
license    : GPL-2.0
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager applet and GTK3 libraries
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
    - pkgconfig(mobile-broadband-provider-info)
    - gtk-doc
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %patch -p1 < $pkgfiles/Fix-saving-imported-vpns.patch
    %meson_configure -Dlibnm-gtk=true -Dselinux=false
build      : |
    %meson_build
install    : |
    %meson_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
