name       : network-manager-applet
version    : 1.0.10
release    : 13
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/network-manager-applet/1.0/network-manager-applet-1.0.10.tar.xz : b045ac3eaa68ccbbefe91510ad67b4002a7e09d1e5ce1c4bf9a67619bd2cf0eb
license    :
    - GPL-2.0
summary    : NetworkManager Applet
builddeps  :
    - pkgconfig(libnm-glib)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libnotify)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gobject-introspection-1.0)
rundeps    :
    - mobile-broadband-provider-info
description: |
    NetworkManager applet and GTK3 libraries
setup      : |
    %configure --disable-static \
               --disable-migration
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
