name       : network-manager-applet
version    : 1.4.6
release    : 20
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.4/network-manager-applet-1.4.6.tar.xz : 10a6fcfe8c6206cf18ec78a522a716b5ec9d0b7ca1e7d234c638725b316fec76
license    : GPL-2.0
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager applet and GTK3 libraries
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %configure --disable-static \
               --disable-migration \
               --without-selinux
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
