name       : network-manager-applet
version    : 1.26.0
release    : 46
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.26/network-manager-applet-1.26.0.tar.xz : 69611b29064adbd57395fe3e51a9ebde1ea794615f776900453a2bbe3d8cddfd
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager Applet
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
setup      : |
    %meson_configure --sysconfdir=/usr/share/ -Dappindicator=no -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
