name        : network-manager-applet
version     : 1.0.2
release     : 10
source      :
    - http://ftp.gnome.org/pub/gnome/sources/network-manager-applet/1.0/network-manager-applet-1.0.2.tar.xz : 760af85b43fa5bcf74b96f899a6d4c1d5e9445e5eb63088c49e5164bbf88d9a9
license     :
    - GPL-2.0
summary     : NetworkManager Applet
builddeps   :
    - pkgconfig(libnm-glib)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libnotify)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
description : |
    NetworkManager applet and GTK3 libraries
setup      : |
    %patch -p1 < $pkgfiles/0001-Temp-Show-in-GNOME-so-that-new-Budgie-can-use-nm-app.patch
    %configure --disable-static \
               --disable-migration
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
