name       : network-manager-applet
version    : 1.16.0
release    : 36
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.16/network-manager-applet-1.16.0.tar.xz : d6f98a455a271e7e169b5d35d290f4880f503cdf7593251572c9330941b5c3e5
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager Applet
builddeps  :
    - pkgconfig(jansson)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
    - libnma-devel # Need to use this until network-manager-applet is indexed and conflicting pkgconfig is removed
setup      : |
    %meson_configure --sysconfdir=/usr/share/ -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
