name       : network-manager-applet
version    : 1.32.0
release    : 51
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.32/network-manager-applet-1.32.0.tar.xz : a2b5affa1505ad43902959fdbe09e5bcec57b11ed333fa60458ffb9c62efba38
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager Applet
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnma)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
setup      : |
    %meson_configure --sysconfdir=/usr/share/ -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
