name       : network-manager-applet
version    : 1.8.6
release    : 24
source     :
    - git|https://git.gnome.org/browse/network-manager-applet : 3d7c0a89da37074e6986262d4708d4093bf496f2
license    : GPL-2.0
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager applet and GTK3 libraries
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
    - gtk-doc
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %meson_configure -Denable-selinux=false -Denable-libnm-gtk=true
build      : |
    %meson_build
install    : |
    %meson_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
