name       : network-manager-applet
version    : 1.4.2
release    : 15
source     :
    - https://ftp.gnome.org/pub/gnome/sources/network-manager-applet/1.4/network-manager-applet-1.4.2.tar.xz : 431b7b4876638c6a537c8bf9c91a9250532b3d960b22b056df554695a81e4499
license    : GPL-2.0
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager applet and GTK3 libraries
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnm-glib)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %configure --disable-static \
               --disable-migration
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
